services:
  - type: web
    name: xforum
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && mkdir -p /var/data && chmod 777 /var/data && flask db upgrade"
    startCommand: "gunicorn run:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: SECRET_KEY
        generateValue: true
      - fromGroup: xforum-gmail-env
    disks:
      - name: forum-data
        mountPath: /var/data
        sizeGB: 1

envVarGroups:
  - name: xforum-gmail-env
    envVars:
      - key: DATABASE_URL
        value: "sqlite:////var/data/forum.db"
      - key: MAIL_SERVER
        value: "smtp.googlemail.com"
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USE_TLS
        value: "true"
      - key: MAIL_USERNAME
        value: "islamhriday625@gmail.com"
      - key: MAIL_PASSWORD
        value: "jnekxaseoxemgjjb"
      - key: MAIL_DEFAULT_SENDER
        value: "islamhriday625@gmail.com"
